#!/usr/bin/with-contenv bash

# Make folders
mkdir -p $INSTALL_LOCATION $DOWNLOAD_LOCATION

# Fix permissions
chown -R dockeruser:dockeruser $INSTALL_LOCATION
chown -R dockeruser:dockeruser $DOWNLOAD_LOCATION
chown -R dockeruser:dockeruser $CONF_TMP
