#!/usr/bin/with-contenv bash

# Make folders
mkdir -p $TRACCAR_VOL{/conf,/data,/logs}

# Check if Traccar config files exists, else copy default ones
for file in default traccar; do
    if [ -f "$TRACCAR_VOL/conf/$file.xml" ];then
        echo "Le fichier $TRACCAR_VOL/conf/$file.xml existe";
    else
        echo "Le fichier $TRACCAR_VOL/conf/$file.xml n'existe pas, copie du fichier par défaut"
        cp $TRACCAR_VOL/init-conf/$file.xml $TRACCAR_VOL/conf/$file.xml
    fi
done

# Fix permissions
chown -R dockeruser:dockeruser $TRACCAR_VOL

# Working dir
cd $TRACCAR_VOL
